export enum AppEnv {
  ENVIRONMENT = "",
  GRAPH_API_VERSION = "GRAPH_API_VERSION",
  TEST_IMAGE_URL = "TEST_IMAGE_URL",
  TELEGRAM_REPORT_CHANNEL_ID = "TELEGRAM_REPORT_CHANNEL_ID",
  EMBEDDER_HOST = "EMBEDDER_HOST",
  TYPESENSE_HOST = "TYPESENSE_HOST",
  TYPESENSE_PORT = "TYPESENSE_PORT",
  TYPESENSE_PROTOCOL = "TYPESENSE_PROTOCOL",
  SIMILARITY_THRESHOLD = "SIMILARITY_THRESHOLD",
  CHECKER1_PHONE_NUMBER = "CHECKER1_PHONE_NUMBER",
}
